version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: r4e-ms-bikers-db
    restart: always
    environment:
      MYSQL_DATABASE: 'r4e-bikers'
      MYSQL_USER: 'r4e'
      MYSQL_PASSWORD: 'R1de 4 3ver with bikers!'
      MYSQL_ROOT_PASSWORD: 'R1de 4 3ver!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ride4ever-bikers-db:/var/lib/mysql

volumes:
  ride4ever-bikers-db:
